name: work_key
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons:
  dio:
  flutter_bloc:
  equatable:
  shared_preferences:
  hexcolor:
  pin_code_fields:
  file_picker:
  image_picker:
  google_nav_bar:
  flutter_radio_group:
  flutter_holo_date_picker:
  intl:
  dropdown_button2:
  font_awesome_flutter:
  smooth_page_indicator:
  url_launcher:
  livekit_client:
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

flutter_launcher_icons:
  image_path: assets/images/app_icon.png
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#FDFDFD"
  adaptive_icon_foreground: assets/images/app_icon.png
  web:
    generate: true
    image_path: assets/images/app_icon.png
    background_color: "#F7F9F8"
    theme_color: "#18A949"
  windows:
    generate: true
    image_path: assets/images/app_icon.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/images/app_icon.png
